<?php

declare(strict_types=1);

/**
 * Mucan Package
 *
 * @copyright Mucan (https://github.com/mucan54)
 */

?>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$width = (int)$block->getWidth();
$paddingBottom = $block->getRatio() * 100;
$badgeImage = $block->getBadgeImage();
$badgeColor = $block->getBadgeColor();
$badgeTextColor = $block->getBadgeTextColor();
$badgeWidth = ($block->getBadgeWidth() ?? 40) . 'px';
$badgeHeight = ($block->getBadgeHeight() ?? 40) . 'px';
?>
<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>">
    <span class="product-image-wrapper">
        <div class="badge-container"
              alt="<?= $escaper->escapeHtmlAttr($block->getBadgeName()) ?>"
              style="<?= $badgeColor ? "background-color: $badgeColor;" : "" ?><?= $badgeImage ? "background-image: url('$badgeImage');" : "" ?>
              <?= "width: $badgeWidth; height: $badgeHeight;" ?>">
            <span class="badge-container-text" style="<?= $badgeTextColor ? "color: $badgeTextColor;" : "" ?>" >
                <?= $escaper->escapeHtmlAttr($block->getBadgeText()) ?>
            </span>
        </div>
        <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>"
            <?php endforeach; ?>
            src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"/></span>
</span>
<?php
$styles = <<<STYLE
.product-image-container-{$block->getProductId()} {
    width: {$width}px;
}
.product-image-container-{$block->getProductId()} span.product-image-wrapper {
    padding-bottom: {$paddingBottom}%;
}
STYLE;
//In case a script was using "style" attributes of these elements
$script = <<<SCRIPT
prodImageContainers = document.querySelectorAll(".product-image-container-{$block->getProductId()}");
for (var i = 0; i < prodImageContainers.length; i++) {
    prodImageContainers[i].style.width = "{$width}px";
}
prodImageContainersWrappers = document.querySelectorAll(
    ".product-image-container-{$block->getProductId()}  span.product-image-wrapper"
);
for (var i = 0; i < prodImageContainersWrappers.length; i++) {
    prodImageContainersWrappers[i].style.paddingBottom = "{$paddingBottom}%";
}
SCRIPT;

?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styles, false) ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>
